
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action TargetAction;
	private global::Gtk.RadioAction ObjectPascalAction;
	private global::Gtk.RadioAction PHPAction;
	private global::Gtk.Action OpenFileSAction;
	private global::Gtk.Action ExitAction;
	private global::Gtk.Action FontAction;
	private global::Gtk.Action SettingsAction;
	private global::Gtk.Action SaveTargetSAction;
	private global::Gtk.Action TranslateAction;
	private global::Gtk.ToggleAction AutoTranslateAction;
	private global::Gtk.Action SaveSourceSAction;
	private global::Gtk.Action Action;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Entry iNameSpace;
	private global::Gtk.ComboBox cbLanguage;
	private global::Gtk.HBox hbox1;
	private global::Gtk.VBox vbSource;
	private global::Gtk.ComboBox cbSource;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView tvSource;
	private global::Gtk.VBox vbTarget;
	private global::Gtk.ComboBox cbTarget;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TextView tvTarget;
	private global::Gtk.Label lbMsg;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("_File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_File");
		w1.Add (this.FileAction, null);
		this.TargetAction = new global::Gtk.Action ("TargetAction", global::Mono.Unix.Catalog.GetString ("_Target"), null, null);
		this.TargetAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Target");
		w1.Add (this.TargetAction, null);
		this.ObjectPascalAction = new global::Gtk.RadioAction ("ObjectPascalAction", global::Mono.Unix.Catalog.GetString ("Object Pascal"), null, null, 0);
		this.ObjectPascalAction.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.ObjectPascalAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Object Pascal");
		w1.Add (this.ObjectPascalAction, null);
		this.PHPAction = new global::Gtk.RadioAction ("PHPAction", global::Mono.Unix.Catalog.GetString ("PHP"), null, null, 0);
		this.PHPAction.Group = this.ObjectPascalAction.Group;
		this.PHPAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("PHP");
		w1.Add (this.PHPAction, null);
		this.OpenFileSAction = new global::Gtk.Action ("OpenFileSAction", global::Mono.Unix.Catalog.GetString ("_Open file(s)"), null, null);
		this.OpenFileSAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Open");
		w1.Add (this.OpenFileSAction, null);
		this.ExitAction = new global::Gtk.Action ("ExitAction", global::Mono.Unix.Catalog.GetString ("E_xit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("E_xit");
		w1.Add (this.ExitAction, null);
		this.FontAction = new global::Gtk.Action ("FontAction", global::Mono.Unix.Catalog.GetString ("F_ont"), null, null);
		this.FontAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("F_ont");
		w1.Add (this.FontAction, null);
		this.SettingsAction = new global::Gtk.Action ("SettingsAction", global::Mono.Unix.Catalog.GetString ("_Settings"), null, null);
		this.SettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Settings");
		w1.Add (this.SettingsAction, null);
		this.SaveTargetSAction = new global::Gtk.Action ("SaveTargetSAction", global::Mono.Unix.Catalog.GetString ("Save target(s)"), null, null);
		this.SaveTargetSAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save targets");
		w1.Add (this.SaveTargetSAction, null);
		this.TranslateAction = new global::Gtk.Action ("TranslateAction", global::Mono.Unix.Catalog.GetString ("Translate"), null, null);
		this.TranslateAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Translate");
		w1.Add (this.TranslateAction, null);
		this.AutoTranslateAction = new global::Gtk.ToggleAction ("AutoTranslateAction", global::Mono.Unix.Catalog.GetString ("Auto translate"), null, null);
		this.AutoTranslateAction.Active = true;
		this.AutoTranslateAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Auto translate");
		w1.Add (this.AutoTranslateAction, null);
		this.SaveSourceSAction = new global::Gtk.Action ("SaveSourceSAction", global::Mono.Unix.Catalog.GetString ("Save source(s)"), null, null);
		this.SaveSourceSAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save source(s)");
		w1.Add (this.SaveSourceSAction, null);
		this.Action = new global::Gtk.Action ("Action", global::Mono.Unix.Catalog.GetString ("---"), null, null);
		this.Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("---");
		w1.Add (this.Action, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(2));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='OpenFileSAction' action='OpenFileSAction'/><menuitem name='TranslateAction' action='TranslateAction'/><menuitem name='SaveSourceSAction' action='SaveSourceSAction'/><menuitem name='SaveTargetSAction' action='SaveTargetSAction'/><menuitem name='ExitAction' action='ExitAction'/></menu><menu name='SettingsAction' action='SettingsAction'><menuitem name='FontAction' action='FontAction'/><menuitem name='AutoTranslateAction' action='AutoTranslateAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Homogeneous = true;
		this.hbox2.Spacing = 2;
		// Container child hbox2.Gtk.Box+BoxChild
		this.iNameSpace = new global::Gtk.Entry ();
		this.iNameSpace.CanFocus = true;
		this.iNameSpace.Name = "iNameSpace";
		this.iNameSpace.Text = global::Mono.Unix.Catalog.GetString ("namespace");
		this.iNameSpace.IsEditable = true;
		this.iNameSpace.InvisibleChar = '●';
		this.hbox2.Add (this.iNameSpace);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.iNameSpace]));
		w3.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.cbLanguage = global::Gtk.ComboBox.NewText ();
		this.cbLanguage.Name = "cbLanguage";
		this.hbox2.Add (this.cbLanguage);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.cbLanguage]));
		w4.Position = 1;
		w4.Expand = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Homogeneous = true;
		this.hbox1.Spacing = 2;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbSource = new global::Gtk.VBox ();
		this.vbSource.Name = "vbSource";
		// Container child vbSource.Gtk.Box+BoxChild
		this.cbSource = global::Gtk.ComboBox.NewText ();
		this.cbSource.Name = "cbSource";
		this.vbSource.Add (this.cbSource);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbSource [this.cbSource]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbSource.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.tvSource = new global::Gtk.TextView ();
		this.tvSource.CanFocus = true;
		this.tvSource.Name = "tvSource";
		this.GtkScrolledWindow.Add (this.tvSource);
		this.vbSource.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbSource [this.GtkScrolledWindow]));
		w8.Position = 1;
		this.hbox1.Add (this.vbSource);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbSource]));
		w9.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbTarget = new global::Gtk.VBox ();
		this.vbTarget.Name = "vbTarget";
		// Container child vbTarget.Gtk.Box+BoxChild
		this.cbTarget = global::Gtk.ComboBox.NewText ();
		this.cbTarget.Name = "cbTarget";
		this.vbTarget.Add (this.cbTarget);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbTarget [this.cbTarget]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbTarget.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.tvTarget = new global::Gtk.TextView ();
		this.tvTarget.CanFocus = true;
		this.tvTarget.Name = "tvTarget";
		this.tvTarget.Editable = false;
		this.GtkScrolledWindow1.Add (this.tvTarget);
		this.vbTarget.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbTarget [this.GtkScrolledWindow1]));
		w12.Position = 1;
		this.hbox1.Add (this.vbTarget);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbTarget]));
		w13.Position = 1;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w14.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.lbMsg = new global::Gtk.Label ();
		this.lbMsg.Name = "lbMsg";
		this.lbMsg.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.vbox1.Add (this.lbMsg);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.lbMsg]));
		w15.PackType = ((global::Gtk.PackType)(1));
		w15.Position = 3;
		w15.Expand = false;
		w15.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 553;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.OpenFileSAction.Activated += new global::System.EventHandler (this.OnOpen);
		this.ExitAction.Activated += new global::System.EventHandler (this.OnExit);
		this.FontAction.Activated += new global::System.EventHandler (this.OnFontItem);
		this.SaveTargetSAction.Activated += new global::System.EventHandler (this.OnSaveTarget);
		this.TranslateAction.Activated += new global::System.EventHandler (this.OnTranslate);
		this.AutoTranslateAction.Toggled += new global::System.EventHandler (this.OnSourceChange);
		this.SaveSourceSAction.Activated += new global::System.EventHandler (this.OnSaveSource);
		this.cbLanguage.Changed += new global::System.EventHandler (this.OnLanguageChange);
		this.cbSource.Changed += new global::System.EventHandler (this.cbSourceChanged);
		this.cbTarget.Changed += new global::System.EventHandler (this.cbTargetChanged);
	}
}
